-- MySQL Script generated by MySQL Workbench
-- Tue Jun 30 09:22:24 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `codigo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(60) NOT NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  `telefone_cliente` VARCHAR(15) NOT NULL,
  `email_cliente` VARCHAR(60) NOT NULL,
  `cep_cliente` VARCHAR(8) NOT NULL,
  `endereco_cliente` VARCHAR(50) NOT NULL,
  `data_nascimento_cliente` DATE NOT NULL,
  `sexo_cliente` ENUM("Masculino", "Feminino", "Outros") NOT NULL,
  `genero_cliente` VARCHAR(30) NULL,
  `etnia_cliente` VARCHAR(30) NOT NULL,
  `nome_social_cliente` VARCHAR(60) NULL,
  `estado_civil_cliente` VARCHAR(30) NOT NULL,
  `data_cadastro_cliente` DATE NULL DEFAULT current timestamp(),
  PRIMARY KEY (`codigo_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIO` (
  `codigo_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(60) NOT NULL,
  `cpf_funcionario` VARCHAR(11) NOT NULL,
  `rg_funcionario` VARCHAR(11) NOT NULL,
  `certidao_nascimento_filho` VARCHAR(30) NULL,
  `certificado_reservista` VARCHAR(12) NULL,
  `certidao_casamento` VARCHAR(30) NULL,
  `titulo_eleitor` VARCHAR(11) NULL,
  `telefone_funcionario` VARCHAR(15) NULL,
  `email_funcionario` VARCHAR(60) NOT NULL,
  `cep_funcionario` VARCHAR(8) NOT NULL,
  `endereco_funcionario` VARCHAR(50) NOT NULL,
  `data_nascimento_funcionario` DATE NOT NULL,
  `sexo_funcionario` ENUM("Masculino", "Feminino", "Outros") NULL,
  `genero_funcionario` VARCHAR(30) NULL,
  `etnia_funcionario` VARCHAR(30) NOT NULL,
  `nome_social_funcionario` VARCHAR(60) NULL,
  `data_admissao` DATE NULL DEFAULT current_timestamp(),
  `data_demissao` DATE NULL,
  `escolaridade` ENUM("Fundamental", "Médio", "Graduação", "Pós-Graduação") NULL,
  `pis` VARCHAR(11) NOT NULL,
  `carteira_trabalho` VARCHAR(11) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `codigo_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(30) NOT NULL,
  `categoria` VARCHAR(30) NOT NULL,
  `descricao_produto` TEXT NULL,
  `fabricante` VARCHAR(30) NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `preco_produto` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`codigo_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTOQUE` (
  `codigo_estoque` INT NOT NULL AUTO_INCREMENT,
  `codigo_produto` INT NOT NULL,
  `fabricacao` DATE NOT NULL,
  `validade` DATE NOT NULL,
  `ESTOQUEcol` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_estoque`),
  INDEX `fk_ESTOQUE_PRODUTO_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_ESTOQUE_PRODUTO`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `mydb`.`PRODUTO` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDA` (
  `codigo_venda` INT NOT NULL AUTO_INCREMENT,
  `codigo_cliente` INT NOT NULL,
  `codigo_funcionario` INT NOT NULL,
  `data_hora` DATE NULL DEFAULT current_timestamp(),
  `total` DECIMAL(7,2) NULL,
  PRIMARY KEY (`codigo_venda`),
  INDEX `fk_VENDA_CLIENTE1_idx` (`codigo_cliente` ASC) VISIBLE,
  INDEX `fk_VENDA_FUNCIONARIO1_idx` (`codigo_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_VENDA_CLIENTE1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `mydb`.`CLIENTE` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_FUNCIONARIO1`
    FOREIGN KEY (`codigo_funcionario`)
    REFERENCES `mydb`.`FUNCIONARIO` (`codigo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITENS_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITENS_VENDA` (
  `codigo_itens_venda` INT NOT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `PRODUTO_codigo_produto` INT NOT NULL,
  `desconto` DECIMAL(4,2) NULL,
  `quantidade` INT NOT NULL,
  `subtotal` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_itens_venda`),
  INDEX `fk_ITENS_VENDA_VENDA1_idx` (`codigo_venda` ASC) VISIBLE,
  INDEX `fk_ITENS_VENDA_PRODUTO1_idx` (`PRODUTO_codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_ITENS_VENDA_VENDA1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`VENDA` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITENS_VENDA_PRODUTO1`
    FOREIGN KEY (`PRODUTO_codigo_produto`)
    REFERENCES `mydb`.`PRODUTO` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGAMENTO` (
  `codigo_pagamento` INT NOT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `forma_pagamento` VARCHAR(20) NOT NULL,
  `informacao_cartao` VARCHAR(30) NOT NULL,
  `total_pagamento` DECIMAL(7,2) NOT NULL,
  `valor_recebido` DECIMAL(7,2) NOT NULL,
  `troco` DECIMAL(7,2) NULL,
  `numero_parcelas` INT NULL,
  `valor_parcela` DECIMAL(7,2) NULL,
  `status_pagamento` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo_pagamento`),
  INDEX `fk_PAGAMENTO_VENDA1_idx` (`codigo_venda` ASC) VISIBLE,
  CONSTRAINT `fk_PAGAMENTO_VENDA1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`VENDA` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
